f1=open(r"C:\Users\divya aghi\PycharmProjects\Python_SDET\Practice session 20\file1.txt","w")
f1.write("This is first file\n")
f1.write("This is a text file")
f1.close()
print("File1 created")
f2=open(r"C:\Users\divya aghi\PycharmProjects\Python_SDET\Practice session 20\file2.txt","w")
f2.write("This is a second file\n")
f2.close()
print("File2 created")

f3=open(r"C:\Users\divya aghi\PycharmProjects\Python_SDET\Practice session 20\file1.txt","r")
s=f3.read()
f4=open(r"C:\Users\divya aghi\PycharmProjects\Python_SDET\Practice session 20\file2.txt","a")
f4.write(s)
print("Done")