file1=open(r"C:\Users\divya aghi\PycharmProjects\Python_SDET\Practice session 20\source.txt","w")
file1.write("This is a first file\n")
file1.write("It consists of data for exam preparation\n")
file1.close()
print("File1 created")
file2=open(r"C:\Users\divya aghi\PycharmProjects\Python_SDET\Practice session 20\destination.txt","w")
file2.write("This is a second file\n")
file2.write("It consists of data for msts\n")
file2.close()
print("File2 created")
file3=open(r"C:\Users\divya aghi\PycharmProjects\Python_SDET\Practice session 20\source.txt","r")
s=file3.read()
file4=open(r"C:\Users\divya aghi\PycharmProjects\Python_SDET\Practice session 20\destination.txt","a")
file4.write(s)
print("Successfully completed")

