file=open(r"C:\Users\divya aghi\PycharmProjects\Python_SDET\Practice session 20\input.txt","w")
file.write("This is an input file\n")
file.write("It consists of all the inputs which you have to give")
file.close()
print("File created")